# Generated by Django 5.2.4 on 2025-07-08 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_description', models.TextField()),
                ('initial_price', models.PositiveIntegerField()),
                ('current_price', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField()),
                ('product_image', models.ImageField(upload_to='product_images/')),
                ('stock', models.PositiveIntegerField(default=1)),
                ('is_dicounted', models.BooleanField(default=False)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('product_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.seller')),
            ],
        ),
    ]
